version: '3.8'

services:
  # Servicio de Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}

    ports:
      # Exponer el puerto de MySQL al host para debugging (opcional)
      - "3307:3306"
    volumes:
      # Persistir los datos de la base de datos
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Servicio del Backend (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: /bin/sh -c "python wait-for-db.py && python seed_data.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}

      DB_USER_ADMIN: ${DB_USER_ADMIN}
      DB_PASSWORD_ADMIN: ${DB_PASSWORD_ADMIN}

      DB_USER_LOGIN: ${DB_USER_LOGIN}
      DB_PASSWORD_LOGIN: ${DB_PASSWORD_LOGIN}

      DB_USER_USER: ${DB_USER_USER}
      DB_PASSWORD_USER: ${DB_PASSWORD_USER}

      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}



  # Servicio del Frontend (React + Nginx)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: react_frontend
    restart: always
    depends_on:
      - backend
    ports:
      # Exponer el puerto 80 del contenedor al puerto 3000 del host
      - "3000:80"

volumes:
  mysql_data:
